name: generate animation

on:
  schedule: # execute every 5 minutes
    - cron: "*/5 * * * *"
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the main branch
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        with:
          github_user_name: MatheusLTrindade
          outputs: dist/github-contribution-grid-snake.svg


      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
